name: Google Script Deploy
description: Google Script Deploy
branding:
  icon: check
  color: green
inputs:
  github-token:
    description: Github Token
    required: true
  refresh-token:
    description: Google Refresh Token
    required: true
  client-id:
    description: Google Client ID
    required: true
  client-secret:
    description: Google Client Sercret
    required: true
  deploy:
    description: If false, skip Deploy flow.
    required: false
    default: 'true'
  deploy-version-number:
    description: Script Version Number
    required: false
  deploy-description:
    description: Script Deploy Description
    required: false
  deploy-id:
    description: Script Deploy ID
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.refresh-token }}
    - ${{ inputs.client-id }}
    - ${{ inputs.client-secret }}
    - ${{ inputs.deploy }}
    - ${{ inputs.deploy-version-number }}
    - ${{ inputs.deploy-description }}
    - ${{ inputs.deploy-id }}
